// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRAWJECukqLRNZiFur5MGfw6o_EjEsXVI',
    appId: '1:689196520124:web:7698c4f7a707108da4b6b9',
    messagingSenderId: '689196520124',
    projectId: 'fir-1-thing',
    authDomain: 'fir-1-thing.firebaseapp.com',
    storageBucket: 'fir-1-thing.firebasestorage.app',
    measurementId: 'G-BLKNLYP06P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUGpk4Suh0ZjXNNK7YCCikBOwNzOrlVw',
    appId: '1:689196520124:android:a36e2c562d157176a4b6b9',
    messagingSenderId: '689196520124',
    projectId: 'fir-1-thing',
    storageBucket: 'fir-1-thing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOsmqtln2CTNMEPas3M33FvFumYlqjxwQ',
    appId: '1:689196520124:ios:c7920191e44f5074a4b6b9',
    messagingSenderId: '689196520124',
    projectId: 'fir-1-thing',
    storageBucket: 'fir-1-thing.firebasestorage.app',
    iosBundleId: 'com.example.firebaseRodi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOsmqtln2CTNMEPas3M33FvFumYlqjxwQ',
    appId: '1:689196520124:ios:c7920191e44f5074a4b6b9',
    messagingSenderId: '689196520124',
    projectId: 'fir-1-thing',
    storageBucket: 'fir-1-thing.firebasestorage.app',
    iosBundleId: 'com.example.firebaseRodi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRAWJECukqLRNZiFur5MGfw6o_EjEsXVI',
    appId: '1:689196520124:web:3ac50428ee781defa4b6b9',
    messagingSenderId: '689196520124',
    projectId: 'fir-1-thing',
    authDomain: 'fir-1-thing.firebaseapp.com',
    storageBucket: 'fir-1-thing.firebasestorage.app',
    measurementId: 'G-ZT42R2E58L',
  );
}
